Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -67,6 +67,16 @@ jobs:
         name: my-artifact
         path: target/*.jar
 
+    - name: Debug Docker Tag
+      run: echo "Docker Tag:${{ env.new_version_docker }}"
+
+    - name: Ensure valid Docker tag format
+      run: |
+        if [[ ! "${{ env.new_version_docker }}" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
+          echo "Invalid Docker tag format"
+          exit 1
+        fi
+
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
